# The name of the deployment
name: Trigger auto deployment for containerapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    # Branched to look out for changes on
    branches: 
      [ master ]

  # Allow manually trigger of the jobs
  workflow_dispatch:      

jobs:
  # Job run image.
    build:
      runs-on: mcr.microsoft.com/devcontainers/typescript-node

   # Steps that need to happen in this job run.
      steps:
        # Check out the code
        - name: Check out code
          uses: actions/checkout@v2

        # Log in to Azure CLI
        - name: Log in to Azure
          uses: azure/login@v1
          with:
      # Azure CLI credentials
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Build and deploy the container app
        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v0
          with:
            repository: containerhouse.azurecr.io
            registryUrl: containerhouse.azurecr.io
            appSourcePath: ${{ github.workspace }}
            acrName: containerhouse
            acrUsername: ${{ secrets.REGISTRY_USERNAME }}
            acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
            containerAppName: mikeleitz-website
            containerAppEnvironment: prod
            resourceGroup: mikeleitz-website-rg
            imageToBuild: containerhouse/mikeleitz-website:latest
            dockerfilePath: ./Dockerfile