name: Trigger auto deployment for website-spotlight

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/website-spotlight-AutoDeployTrigger-0b23c0fe-24f8-423b-b855-8d7543e3ba9f.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEBSITESPOTLIGHT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerhouse.azurecr.io
          registryUsername: ${{ secrets.WEBSITESPOTLIGHT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBSITESPOTLIGHT_REGISTRY_PASSWORD }}
          containerAppName: website-spotlight
          resourceGroup: mikeleitz-website-rg
          imageToBuild: containerhouse.azurecr.io/website-spotlight:${{ github.sha }}
          
            

     

